CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    --user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    
    -- Авторизация
    login VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL,
    
    -- ФИО
    name_0 VARCHAR(30) NOT NULL,
    name_1 VARCHAR(30),
    name_2 VARCHAR(30),
    
    -- Личные данные
    snils VARCHAR(30),-- UNIQUE CHECK(snils ~ '^\d{11}$'),
    gender VARCHAR(3),
    birthday DATE,
    
    -- Работа
    role VARCHAR(30),
    tab_num INTEGER UNIQUE,
    department VARCHAR(30), --CHARACTER VARYING
    
    -- Доступы
    card_id VARCHAR(30) UNIQUE,
    code VARCHAR(50) UNIQUE,
    block VARCHAR(30),
    
    -- Технические ID
    set_id INTEGER,
    kas_id INTEGER,
    mesh_id INTEGER,
    doz_tld_id VARCHAR(30),
    
    -- Дозиметрия
    cell_date DATE,
    dose_year NUMERIC(10,2) CHECK(dose_year >= 0), --float8
    dose_year_now NUMERIC(10,2) CHECK(dose_year_now >= 0), --float8
    dose_year_now_ppd NUMERIC(10,2) CHECK(dose_year_now_ppd >= 0), --float8
    
    -- Дозы (периоды)
    start_doz INTEGER,
    finish_doz INTEGER,
    
    -- Системные поля
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Индексы для ускорения поиска
CREATE INDEX IF NOT EXISTS idx_users_login ON users(login);